DROP TABLE ETL_TEMP_CARGA_ATV_GERA_BOLETO_ITAU;

CREATE TABLE ETL_TEMP_CARGA_ATV_GERA_BOLETO_ITAU (
    id INT IDENTITY(1,1) PRIMARY KEY, -- ID com chave primária
    etapa_processo_boleto NVARCHAR(200),
    beneficiario_id_beneficiario NVARCHAR(200),
    dado_boleto_tipo_boleto NVARCHAR(200),
    dado_boleto_descricao_instrumento_cobranca NVARCHAR(200),
    dado_boleto_texto_seu_numero NVARCHAR(200),
    dado_boleto_codigo_carteira NVARCHAR(200),
    dado_boleto_valor_total_titulo NVARCHAR(200),
    dado_boleto_codigo_especie NVARCHAR(200),
    dado_boleto_data_emissao NVARCHAR(200),
    dado_boleto_valor_abatimento NVARCHAR(200),
    negativacao_negativacao NVARCHAR(200),
    negativacao_quantidade_dias_negativacao NVARCHAR(200),
    pagador_pessoa_nome_pessoa NVARCHAR(200),
    pagador_pessoa_nome_fantasia NVARCHAR(200),
    pagador_pessoa_tipo_pessoa_codigo_tipo_pessoa NVARCHAR(200),
    pagador_pessoa_tipo_pessoa_numero_cadastro_pessoa_fisica NVARCHAR(200),
    pagador_endereco_nome_logradouro NVARCHAR(200),
    pagador_endereco_nome_bairro NVARCHAR(200),
    pagador_endereco_nome_cidade NVARCHAR(200),
    pagador_endereco_sigla_UF NVARCHAR(200),
    pagador_endereco_numero_CEP NVARCHAR(200),
    sacador_avalista_pessoa_nome_pessoa NVARCHAR(200),
    sacador_avalista_pessoa_tipo_pessoa_codigo_tipo_pessoa NVARCHAR(200),
    sacador_avalista_pessoa_tipo_pessoa_numero_cadastro_pessoa_fisica NVARCHAR(200),
    sacador_avalista_endereco_nome_logradouro NVARCHAR(200),
    sacador_avalista_endereco_nome_bairro NVARCHAR(200),
    sacador_avalista_endereco_nome_cidade NVARCHAR(200),
    sacador_avalista_endereco_sigla_UF NVARCHAR(200),
    sacador_avalista_endereco_numero_CEP NVARCHAR(200),
    dados_individuais_boleto_numero_nosso_numero NVARCHAR(200),
    dados_individuais_boleto_data_vencimento NVARCHAR(200),
    dados_individuais_boleto_texto_uso_beneficiario NVARCHAR(200),
    dados_individuais_boleto_valor_titulo NVARCHAR(200),
    dados_individuais_boleto_data_limite_pagamento NVARCHAR(200),
    juros_data_juros NVARCHAR(200),
    juros_codigo_tipo_juros NVARCHAR(200),
    juros_valor_juros NVARCHAR(200),
    multa_codigo_tipo_multa NVARCHAR(200),
    multa_percentual_multa NVARCHAR(200),
    multa_data_multa NVARCHAR(200),
    descontos_codigo_tipo_desconto NVARCHAR(200),
    descontos_data_desconto NVARCHAR(200),
    descontos_valor_desconto NVARCHAR(200),
    descontos_percentual_desconto NVARCHAR(200),
    dados_qrcode_chave NVARCHAR(200),
    dados_qrcode_id_location NVARCHAR(200),
    TP_STATUS NVARCHAR(200), -- Coluna de status
    json_completo NVARCHAR(MAX), -- Coluna para armazenar todo o JSON
    data_hora_criacao DATETIME DEFAULT GETDATE(), -- Data e hora de criação
    data_hora_alteracao DATETIME DEFAULT GETDATE() -- Data e hora de alteração
);