ALTER PROCEDURE USP_ADICIONAR_BOLETO_ITAU_RETORNO
	@ID_FK BIGINT,
    @codigo_canal_operacao NVARCHAR(200),
    @codigo_operador NVARCHAR(200),
    @etapa_processo_boleto NVARCHAR(200),
    @beneficiario_id_beneficiario NVARCHAR(200),
    @beneficiario_nome_cobranca NVARCHAR(200),
    @beneficiario_tipo_pessoa_codigo_tipo_pessoa NVARCHAR(200),
    @beneficiario_tipo_pessoa_numero_cadastro_nacional_pessoa_juridica NVARCHAR(200),
    @beneficiario_endereco_nome_logradouro NVARCHAR(200),
    @beneficiario_endereco_nome_bairro NVARCHAR(200),
    @beneficiario_endereco_nome_cidade NVARCHAR(200),
    @beneficiario_endereco_sigla_UF NVARCHAR(200),
    @beneficiario_endereco_numero_CEP NVARCHAR(200),
    @beneficiario_endereco_numero NVARCHAR(200),
    @beneficiario_endereco_complemento NVARCHAR(200),
    @dado_boleto_descricao_instrumento_cobranca NVARCHAR(200),
    @dado_boleto_tipo_boleto NVARCHAR(200),
    @dado_boleto_pagador_pessoa_nome_pessoa NVARCHAR(200),
    @dado_boleto_pagador_pessoa_tipo_pessoa_codigo_tipo_pessoa NVARCHAR(200),
    @dado_boleto_pagador_pessoa_tipo_pessoa_numero_cadastro_pessoa_fisica NVARCHAR(200),
    @dado_boleto_pagador_endereco_nome_logradouro NVARCHAR(200),
    @dado_boleto_pagador_endereco_nome_bairro NVARCHAR(200),
    @dado_boleto_pagador_endereco_nome_cidade NVARCHAR(200),
    @dado_boleto_pagador_endereco_sigla_UF NVARCHAR(200),
    @dado_boleto_pagador_endereco_numero_CEP NVARCHAR(200),
    @dado_boleto_codigo_carteira NVARCHAR(200),
    @dado_boleto_codigo_tipo_vencimento NVARCHAR(200),
    @dado_boleto_valor_total_titulo NVARCHAR(200),
    @dados_individuais_boleto_numero_nosso_numero NVARCHAR(200),
    @dados_individuais_boleto_dac_titulo NVARCHAR(200),
    @dados_individuais_boleto_data_vencimento NVARCHAR(200),
    @dados_individuais_boleto_valor_titulo NVARCHAR(200),
    @dados_individuais_boleto_texto_seu_numero NVARCHAR(200),
    @dados_individuais_boleto_codigo_barras NVARCHAR(200),
    @dados_individuais_boleto_numero_linha_digitavel NVARCHAR(200),
    @dados_individuais_boleto_data_limite_pagamento NVARCHAR(200),
    @dados_qrcode_chave NVARCHAR(200),
    @dados_qrcode_txid NVARCHAR(200),
    @dados_qrcode_id_location NVARCHAR(200),
    @dados_qrcode_location NVARCHAR(200),
    @dados_qrcode_emv NVARCHAR(200),
    @dados_qrcode_base64 NVARCHAR(MAX),
    @sn_erro NVARCHAR(200), -- Campo para indicar erro
    @descricao_erro NVARCHAR(500), -- Campo para descrição do erro
    @json_completo NVARCHAR(MAX) -- Coluna para armazenar todo o JSON
AS
BEGIN
    BEGIN TRY
        -- Inserção de dados
        INSERT INTO ETL_TEMP_CARGA_ATV_GERA_BOLETO_ITAU_RETORNO (
            codigo_canal_operacao,
            codigo_operador,
            etapa_processo_boleto,
            beneficiario_id_beneficiario,
            beneficiario_nome_cobranca,
            beneficiario_tipo_pessoa_codigo_tipo_pessoa,
            beneficiario_tipo_pessoa_numero_cadastro_nacional_pessoa_juridica,
            beneficiario_endereco_nome_logradouro,
            beneficiario_endereco_nome_bairro,
            beneficiario_endereco_nome_cidade,
            beneficiario_endereco_sigla_UF,
            beneficiario_endereco_numero_CEP,
            beneficiario_endereco_numero,
            beneficiario_endereco_complemento,
            dado_boleto_descricao_instrumento_cobranca,
            dado_boleto_tipo_boleto,
            dado_boleto_pagador_pessoa_nome_pessoa,
            dado_boleto_pagador_pessoa_tipo_pessoa_codigo_tipo_pessoa,
            dado_boleto_pagador_pessoa_tipo_pessoa_numero_cadastro_pessoa_fisica,
            dado_boleto_pagador_endereco_nome_logradouro,
            dado_boleto_pagador_endereco_nome_bairro,
            dado_boleto_pagador_endereco_nome_cidade,
            dado_boleto_pagador_endereco_sigla_UF,
            dado_boleto_pagador_endereco_numero_CEP,
            dado_boleto_codigo_carteira,
            dado_boleto_codigo_tipo_vencimento,
            dado_boleto_valor_total_titulo,
            dados_individuais_boleto_numero_nosso_numero,
            dados_individuais_boleto_dac_titulo,
            dados_individuais_boleto_data_vencimento,
            dados_individuais_boleto_valor_titulo,
            dados_individuais_boleto_texto_seu_numero,
            dados_individuais_boleto_codigo_barras,
            dados_individuais_boleto_numero_linha_digitavel,
            dados_individuais_boleto_data_limite_pagamento,
            dados_qrcode_chave,
            dados_qrcode_txid,
            dados_qrcode_id_location,
            dados_qrcode_location,
            dados_qrcode_emv,
            dados_qrcode_base64,
            tp_status, -- Novo campo adicionado
            sn_erro, -- Campo para indicar erro
            descricao_erro, -- Campo para descrição do erro
            json_completo,
            data_hora_criacao,
			id_envio_fk
        ) VALUES (
            @codigo_canal_operacao,
            @codigo_operador,
            @etapa_processo_boleto,
            @beneficiario_id_beneficiario,
            @beneficiario_nome_cobranca,
            @beneficiario_tipo_pessoa_codigo_tipo_pessoa,
            @beneficiario_tipo_pessoa_numero_cadastro_nacional_pessoa_juridica,
            @beneficiario_endereco_nome_logradouro,
            @beneficiario_endereco_nome_bairro,
            @beneficiario_endereco_nome_cidade,
            @beneficiario_endereco_sigla_UF,
            @beneficiario_endereco_numero_CEP,
            @beneficiario_endereco_numero,
            @beneficiario_endereco_complemento,
            @dado_boleto_descricao_instrumento_cobranca,
            @dado_boleto_tipo_boleto,
            @dado_boleto_pagador_pessoa_nome_pessoa,
            @dado_boleto_pagador_pessoa_tipo_pessoa_codigo_tipo_pessoa,
            @dado_boleto_pagador_pessoa_tipo_pessoa_numero_cadastro_pessoa_fisica,
            @dado_boleto_pagador_endereco_nome_logradouro,
            @dado_boleto_pagador_endereco_nome_bairro,
            @dado_boleto_pagador_endereco_nome_cidade,
            @dado_boleto_pagador_endereco_sigla_UF,
            @dado_boleto_pagador_endereco_numero_CEP,
            @dado_boleto_codigo_carteira,
            @dado_boleto_codigo_tipo_vencimento,
            @dado_boleto_valor_total_titulo,
            @dados_individuais_boleto_numero_nosso_numero,
            @dados_individuais_boleto_dac_titulo,
            @dados_individuais_boleto_data_vencimento,
            @dados_individuais_boleto_valor_titulo,
            @dados_individuais_boleto_texto_seu_numero,
            @dados_individuais_boleto_codigo_barras,
            @dados_individuais_boleto_numero_linha_digitavel,
            @dados_individuais_boleto_data_limite_pagamento,
            @dados_qrcode_chave,
            @dados_qrcode_txid,
            @dados_qrcode_id_location,
            @dados_qrcode_location,
            @dados_qrcode_emv,
            @dados_qrcode_base64,
            'A', -- tp_status definido como 'A'
            @sn_erro,
            @descricao_erro,
            @json_completo,
            GETDATE(), -- data_hora_criacao
			@ID_FK
        );

        PRINT 'Registro inserido com sucesso.';

        -- Chamada à outra procedure para atualizar os dados        
		EXEC USP_STG_GERA_BOLETO_ITAU 
		@ID_PK = @ID_FK,
		@etapa_processo_boleto = NULL,
		@beneficiario_id_beneficiario = NULL,
		@dado_boleto_tipo_boleto = NULL,
		@dado_boleto_descricao_instrumento_cobranca = NULL,
		@dado_boleto_texto_seu_numero = NULL,
		@dado_boleto_codigo_carteira = NULL,
		@dado_boleto_valor_total_titulo = NULL,
		@dado_boleto_codigo_especie = NULL,
		@dado_boleto_data_emissao = NULL,
		@dado_boleto_valor_abatimento = NULL,
		@negativacao_negativacao = NULL,
		@negativacao_quantidade_dias_negativacao = NULL,
		@pagador_pessoa_nome_pessoa = NULL,
		@pagador_pessoa_nome_fantasia = NULL,
		@pagador_pessoa_tipo_pessoa_codigo_tipo_pessoa = NULL,
		@pagador_pessoa_tipo_pessoa_numero_cadastro_pessoa_fisica = NULL,
		@pagador_endereco_nome_logradouro = NULL,
		@pagador_endereco_nome_bairro = NULL,
		@pagador_endereco_nome_cidade = NULL,
		@pagador_endereco_sigla_UF = NULL,
		@pagador_endereco_numero_CEP = NULL,
		@sacador_avalista_pessoa_nome_pessoa = NULL,
		@sacador_avalista_pessoa_tipo_pessoa_codigo_tipo_pessoa = NULL,
		@sacador_avalista_pessoa_tipo_pessoa_numero_cadastro_pessoa_fisica = NULL,
		@sacador_avalista_endereco_nome_logradouro = NULL,
		@sacador_avalista_endereco_nome_bairro = NULL,
		@sacador_avalista_endereco_nome_cidade = NULL,
		@sacador_avalista_endereco_sigla_UF = NULL,
		@sacador_avalista_endereco_numero_CEP = NULL,
		@dados_individuais_boleto_numero_nosso_numero = NULL,
		@dados_individuais_boleto_data_vencimento = NULL,
		@dados_individuais_boleto_texto_uso_beneficiario = NULL,
		@dados_individuais_boleto_valor_titulo = NULL,
		@dados_individuais_boleto_data_limite_pagamento = NULL,
		@juros_data_juros = NULL,
		@juros_codigo_tipo_juros = NULL,
		@juros_valor_juros = NULL,
		@multa_codigo_tipo_multa = NULL,
		@multa_percentual_multa = NULL,
		@multa_data_multa = NULL,
		@descontos_codigo_tipo_desconto = NULL,
		@descontos_data_desconto = NULL,
		@descontos_valor_desconto = NULL,
		@descontos_percentual_desconto = NULL,
		@dados_qrcode_chave = NULL,
		@dados_qrcode_id_location = NULL,
		@TP_STATUS = 'E', -- Novo status
		@json_completo = NULL,
		@Acao = 'U';

    END TRY
    BEGIN CATCH
        PRINT 'Erro ao inserir registro: ' + ERROR_MESSAGE();
        -- Aqui você pode adicionar lógica para tratamento de erro, se necessário
    END CATCH
END
