SELECT * FROM ETL_TEMP_CARGA_ATV_GERA_BOLETO_ITAU;

EXEC USP_STG_GERA_BOLETO_ITAU 
    @etapa_processo_boleto = 'Etapa 1',
    @beneficiario_id_beneficiario = '123456',
    @dado_boleto_tipo_boleto = 'Boleto',
    @dado_boleto_descricao_instrumento_cobranca = 'Descrição 1',
    @dado_boleto_texto_seu_numero = '1234567890',
    @dado_boleto_codigo_carteira = '01',
    @dado_boleto_valor_total_titulo = '150.00',
    @dado_boleto_codigo_especie = 'R$',
    @dado_boleto_data_emissao = '2024-10-21',
    @dado_boleto_valor_abatimento = '0.00',
    @negativacao_negativacao = 'N',
    @negativacao_quantidade_dias_negativacao = '0',
    @pagador_pessoa_nome_pessoa = 'Fulano de Tal',
    @pagador_pessoa_nome_fantasia = 'Empresa ABC',
    @pagador_pessoa_tipo_pessoa_codigo_tipo_pessoa = 'F',
    @pagador_pessoa_tipo_pessoa_numero_cadastro_pessoa_fisica = '12345678901',
    @pagador_endereco_nome_logradouro = 'Rua Exemplo',
    @pagador_endereco_nome_bairro = 'Centro',
    @pagador_endereco_nome_cidade = 'Cidade XYZ',
    @pagador_endereco_sigla_UF = 'SP',
    @pagador_endereco_numero_CEP = '01001000',
    @sacador_avalista_pessoa_nome_pessoa = 'Sacador Avalista',
    @sacador_avalista_pessoa_tipo_pessoa_codigo_tipo_pessoa = 'J',
    @sacador_avalista_pessoa_tipo_pessoa_numero_cadastro_pessoa_fisica = '12345678000199',
    @sacador_avalista_endereco_nome_logradouro = 'Rua Avalista',
    @sacador_avalista_endereco_nome_bairro = 'Bairro Avalista',
    @sacador_avalista_endereco_nome_cidade = 'Cidade Avalista',
    @sacador_avalista_endereco_sigla_UF = 'RJ',
    @sacador_avalista_endereco_numero_CEP = '02002000',
    @dados_individuais_boleto_numero_nosso_numero = '9876543210',
    @dados_individuais_boleto_data_vencimento = '2024-11-21',
    @dados_individuais_boleto_texto_uso_beneficiario = 'Uso do Beneficiário',
    @dados_individuais_boleto_valor_titulo = '150.00',
    @dados_individuais_boleto_data_limite_pagamento = '2024-12-21',
    @juros_data_juros = '2024-11-01',
    @juros_codigo_tipo_juros = '1',
    @juros_valor_juros = '1.00',
    @multa_codigo_tipo_multa = '2',
    @multa_percentual_multa = '2.00',
    @multa_data_multa = '2024-11-01',
    @descontos_codigo_tipo_desconto = '3',
    @descontos_data_desconto = '2024-11-01',
    @descontos_valor_desconto = '5.00',
    @descontos_percentual_desconto = '0.00',
    @dados_qrcode_chave = 'CHAVE123',
    @dados_qrcode_id_location = 'LOCATION123',
    @TP_STATUS = 'PENDENTE',
    @json_completo = '{"data":"exemplo"}',
    @Acao = 'A';


